# SPDX-License-Identifier: MIT
# Copyright (c) 2022 University of California, Riverside

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-checkoutservice
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containerConcurrency: 32
      containers:
      - image: fedeparola/checkoutservice
        name: kn-checkoutservice
        ports:
        - name: h2c
          containerPort: 5050
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:5050"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:5050"]
        env:
        # - name: PORT
        #   value: "5050"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "128.105.146.89:32732"
        - name: SHIPPING_SERVICE_ADDR
          value: "128.105.146.89:32732"
        - name: PAYMENT_SERVICE_ADDR
          value: "128.105.146.89:32732"
        - name: EMAIL_SERVICE_ADDR
          value: "128.105.146.89:32732"
        - name: CURRENCY_SERVICE_ADDR
          value: "128.105.146.89:32732"
        - name: CART_SERVICE_ADDR
          value: "128.105.146.89:32732"
        - name: PRODUCT_CATALOG_SERVICE_URL
          value: "kn-productcatalogservice.default.example.com"
        - name: SHIPPING_SERVICE_URL
          value: "kn-shippingservice.default.example.com"
        - name: PAYMENT_SERVICE_URL
          value: "kn-paymentservice.default.example.com"
        - name: EMAIL_SERVICE_URL
          value: "kn-emailservice.default.example.com"
        - name: CURRENCY_SERVICE_URL
          value: "kn-currencyservice.default.example.com"
        - name: CART_SERVICE_URL
          value: "kn-cartservice.default.example.com"
        - name: DISABLE_STATS
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        # - name: JAEGER_SERVICE_ADDR
        #   value: "jaeger-collector:14268"
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 64Mi
        #   limits:
        #     cpu: 200m
        #     memory: 128Mi
